### ISSUE TITLE
Checking the sensor available

### ISSUE THREAD

**Issue by ITEnDev** [PeterEmbedded/BH1750FVI#10]
Hi!
I am used your library, works good.
But , I have a question.
How can I check that the sensor is working good?
This library is has any function to do this or I have to do a simple I2C address check on other way?
For example: checking the address before read light value from the sensor.

Thanks.

**Comment by PeterEmbedded** [comment]
There is currently no way to be absolutely sure the sensor is present and working correctly. Just checking the address won't help.
When you don't use the sensor in absolute darkness a call to GetLightIntensity() will return a value which is not 0. So just add a small check for the return value to be greater then 0.

**Comment by ITEnDev** [comment]
Thank you for the reply.
Your idea is great, I will use in my sketch. 
Fortunately I don't use the sensor in absolute dark. So, checking the return value is good for me.
Thank you for the help!
