### ISSUE TITLE
Arduino UNO not working

### ISSUE THREAD

**Issue by crashtestoz** [PeterEmbedded/BH1750FVI#8]
Hi I am trying to use your library on an Arduino UNO. I have the SCL pin on A4 and DAT pin on A5.

All I am getting is lux value of 54612

Here is my code:

/*
  This is a simple example to test the BH1750 Light sensor
  
  Connect the sensor to a NodeMCU ESP8266:
  VCC  <-> 3V3 [grey]
  GND  <-> Gnd [purple]
  SDA  <-> D2  [green]
  SCL  <-> D1  [blue]
  ADDR <-> RX  [yellow]
 */

#include <Wire.h>
#include <BH1750FVI.h>

// Settings

int addressPin = A4;
int devicePin = A5;
BH1750FVI::eDeviceMode_t DEVICEMODE = BH1750FVI::k_DevModeContHighRes;

// Create the Lightsensor instance
BH1750FVI LightSensor(addressPin, devicePin, DEVICEMODE);

void setup() 
{
  Serial.begin(9600);
  LightSensor.begin();  
  Serial.println("Running...");
}

void loop()
{
  uint16_t lux = LightSensor.GetLightIntensity();
  Serial.print("Light level: ");
  Serial.println(lux);
  delay(2000);
}

**Comment by PeterEmbedded** [comment]
You should change this part:
```
int addressPin = A4;
int devicePin = A5;
BH1750FVI::eDeviceMode_t DEVICEMODE = BH1750FVI::k_DevModeContHighRes;

// Create the Lightsensor instance
BH1750FVI LightSensor(addressPin, devicePin, DEVICEMODE);
```

to:

```
BH1750FVI::eDeviceAddress_t DEVICEADDRESS = BH1750FVI::k_DevAddress_L;
BH1750FVI::eDeviceMode_t DEVICEMODE = BH1750FVI::k_DevModeContHighRes;

// Create the Lightsensor instance
BH1750FVI LightSensor(ADDRESSPIN, DEVICEADDRESS, DEVICEMODE);
```

`devicePin` in your case has nothing to do with `DEVICEADDRESS`
Just connect the SDA and SCL pins on the BH1750 to the Arduino Uno on pin A4(SDA) and A5(SCL) and connect GND and VCC(3v3).
