### ISSUE TITLE
Wire.beginTransmission() and Wire.endTransmission() should not be used together with Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [PeterEmbedded/BH1750FVI#9]
The function `GetLightIntensity()` should be a `Wire.requestFrom()` with two reads. 
The `Wire.beginTransmission()` and `Wire.endTransmission()` may be removed from that function.
Explanation: [Common-mistakes](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes), number 2 and 3.
See also my [alternative explanation of the functions of the Wire library](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Explanation-of-the-functions-of-the-Wire-library).

**Comment by PeterEmbedded** [comment]
Thanks for the tip.
Fixed.
